require.config({
    baseUrl: '/cache/js/apploader/admin/controller',
    paths: {
      'angular': '/cache/public/js/angular/angular.min',
      'angularAMD': '/cache/public/js/angular/angularAMD.min',
  		'angular-animate': '/cache/public/js/angular/angular-animate.min',
  		'angular-aria': '/cache/public/js/angular/angular-aria.min',
  		'angular-material': '/cache/public/js/angular/angular-material.min',
  		'angular-messages': '/cache/public/js/angular/angular-messages.min',
      'angular-route': '/cache/public/js/angular/angular-route.min',
      'angular-immutable': '/cache/public/js/immutable/angular-immutable.min',
  		'ui-bootstrap-custom': '/cache/public/js/angular/ui-bootstrap-custom-0.12.0.min',
  		'ui-bootstrap-custom-tpls': '/cache/public/js/angular/ui-bootstrap-custom-tpls-0.12.0.min',
  		'reactjs':'/cache/public/js/reactjs/react.min',
  		'ng-flow': '/cache/public/js/ng-flow/ng-flow-standalone.min',
      'moment': '/cache/public/js/moment/moment.min',
      'ngload': '/cache/public/js/requirejs/ngload',
      'calendar-filter': '../filter/calendar-filter',
      'reactloader': '../react/app-react',
      'app': '../app'
    },
	shim: { 'angularAMD': ['angular'],
			'angular-route': ['angular'],
			'angular-animate': ['angular'],
			'angular-aria': ['angular'],
			'angular-material': ['angular'],
			'angular-messages': ['angular'],
			'angular-immutable': ['angular'],
			'ng-flow': ['angular'],
			'reactloader' : ['reactjs'],
			'ui-bootstrap-custom': ['angular'],
			'ui-bootstrap-custom-tpls': ['angular','ui-bootstrap-custom']
			},
	deps:['app']
});
