name: Reusable approval
inputs:
  deployed_url:
    required: true
    type: string
  npm_auth_token:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: ⎔ Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: "npm"
        registry-url: https://npm.pkg.github.com/

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
          ~/.cache/ms-playwright
        key: modules-node-chrome-playwright-${{ hashFiles('package-lock.json') }}

    - name: 📥 Download deps
      shell: bash
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_auth_token }}

    - name: 📥 Install playwright browsers
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: 📸 Run a test to generate snapshot
      shell: bash
      continue-on-error: true
      run: BASE_URL=https://${{ inputs.deployed_url }} npm run visual:test

    - name: 💽 Create an approved snapshot
      shell: bash
      run: BASE_URL=https://${{ inputs.deployed_url }} npm run visual:approve
